import BaseLayoutHome from "@/components/home/BaseLayout";
import React from "react";

export const metadata = {
  title: "Home",
  description: "Generated by Home",
};
export default function LayoutHome({ children }) {
  return <BaseLayoutHome>{children}</BaseLayoutHome>;
}
